version: 0.0
os: windows
hooks:
  BeforeInstall:
  - location: /scripts/deleta-aplicacao.bat
  ApplicationStart:
  - location: /scripts/reinicia-servidor.bat
files:
  - source: ./
    destination: C:\Users\Administrator\Desktop\jboss-eap-6.4.0\jboss-eap-6.4\standalone\deployments